#!/usr/bin/env python3
"""Offline baker for the embedded studio light (spherical-harmonics version).

Decodes the full-resolution Blender forest.exr (DWAB-compressed, so it needs the
OpenEXR Python package) and projects its radiance onto order-2 real spherical
harmonics (9 RGB coefficients). Those coefficients are written into
src/studio_light_data.c and used at runtime for both:
  - diffuse irradiance  E(n)/PI  (Ramamoorthi/Hanrahan cosine-lobe convolution)
  - a roughness-windowed specular radiance approximation

SH is a continuous spherical basis, so there is no equirect pole distortion, and
the whole environment collapses to 27 floats instead of a ~1 MB texture. It only
captures low-frequency lighting, which is exactly what diffuse/rough specular IBL
needs; sharp mirror reflections are intentionally not represented.

Setup (once):  py -m pip install OpenEXR numpy
Run:           py tools/bake_studio_light.py "<path-to-forest.exr>" src/studio_light_data.c
"""

import sys
import numpy as np

SH_ORDER = 2          # bands 0..2  ->  (SH_ORDER+1)^2 = 9 coefficients
SH_COUNT = (SH_ORDER + 1) ** 2


def load_exr_rgb(path):
    import OpenEXR
    f = OpenEXR.File(path)
    chans = f.channels()
    if "RGB" in chans:
        rgb = np.asarray(chans["RGB"].pixels, dtype=np.float32)
    else:
        r = np.asarray(chans["R"].pixels, dtype=np.float32)
        g = np.asarray(chans["G"].pixels, dtype=np.float32)
        b = np.asarray(chans["B"].pixels, dtype=np.float32)
        rgb = np.stack([r, g, b], axis=-1)
    h, w = rgb.shape[0], rgb.shape[1]
    return np.ascontiguousarray(rgb.reshape(h, w, 3)), w, h


def sh_basis(x, y, z):
    """Order-2 orthonormal real SH, matching ShEval* in shaders.c.

    Index order: [Y00, Y1-1(y), Y10(z), Y11(x),
                  Y2-2(xy), Y2-1(yz), Y20(3z^2-1), Y21(xz), Y22(x^2-y^2)]
    """
    return np.stack([
        np.full_like(x, 0.282095),
        0.488603 * y,
        0.488603 * z,
        0.488603 * x,
        1.092548 * x * y,
        1.092548 * y * z,
        0.315392 * (3.0 * z * z - 1.0),
        1.092548 * x * z,
        0.546274 * (x * x - y * y),
    ], axis=-1)


def project_sh(src, w, h):
    """Project an equirect radiance map onto SH using the same direction
    convention as shaders.c (DirToEquirectUV inverse): x=sinT cosP, y=cosT,
    z=sinT sinP, with theta=v*PI, phi=(u-0.5)*2PI."""
    u = (np.arange(w) + 0.5) / w
    v = (np.arange(h) + 0.5) / h
    phi = (u - 0.5) * 2.0 * np.pi
    theta = v * np.pi
    sinT = np.sin(theta)[:, None]                 # (h,1)
    cosT = np.cos(theta)[:, None]
    cosP = np.cos(phi)[None, :]                   # (1,w)
    sinP = np.sin(phi)[None, :]
    x = sinT * cosP
    y = np.broadcast_to(cosT, (h, w))
    z = sinT * sinP

    basis = sh_basis(x, y, z)                     # (h,w,9)
    dω = (sinT * (np.pi / h) * (2.0 * np.pi / w)) # (h,1) solid angle per texel
    weighted = basis * dω[..., None]              # (h,w,9)
    # coeff[k] = sum_pixels radiance * Y_k * dω  ->  (9,3)
    coeffs = np.einsum("hwk,hwc->kc", weighted, src).astype(np.float64)
    return coeffs


def emit(out_path, coeffs):
    with open(out_path, "w", newline="\n") as f:
        f.write(
            "/* Studio light, baked from Blender's forest.exr world HDRI.\n"
            " * Original forest light: Poly Haven / Greg Zaal, CC0.\n"
            " *\n"
            " * Order-2 real spherical-harmonic projection of the HDRI radiance\n"
            " * (9 RGB coefficients, linear). Reconstructed at runtime for diffuse\n"
            " * irradiance and a roughness-windowed specular approximation - see the\n"
            " * ShEval* helpers in shaders.c. Pole-distortion-free and tiny.\n"
            " *\n"
            " * Generated by tools/bake_studio_light.py - do not edit by hand. */\n\n")
        f.write(f"const int studio_sh_count = {SH_COUNT};\n\n")
        f.write("// RGB per coefficient, index order matches ShBasis() in the shader.\n")
        f.write("const float studio_sh_coeffs[] = {\n")
        for k in range(SH_COUNT):
            r, g, b = coeffs[k]
            f.write(f"    {r:+.8e}f, {g:+.8e}f, {b:+.8e}f,\n")
        f.write("};\n")


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <forest.exr> <out studio_light_data.c>", file=sys.stderr)
        return 1
    exr_path, out_path = sys.argv[1], sys.argv[2]

    src, w, h = load_exr_rgb(exr_path)
    print(f"Loaded EXR {w}x{h} from {exr_path}")

    coeffs = project_sh(src, w, h)
    emit(out_path, coeffs)

    # Sanity: DC term reconstructs the average radiance (Y00 * L00).
    avg = src.reshape(-1, 3).mean(axis=0)
    dc = coeffs[0] * 0.282095
    print(f"  SH order {SH_ORDER} ({SH_COUNT} coeffs); DC {dc} vs avg radiance {avg}")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
