/* Studio light, baked from Blender's forest.exr world HDRI.
 * Original forest light: Poly Haven / Greg Zaal, CC0.
 *
 * Order-2 real spherical-harmonic projection of the HDRI radiance
 * (9 RGB coefficients, linear). Reconstructed at runtime for diffuse
 * irradiance and a roughness-windowed specular approximation - see the
 * ShEval* helpers in shaders.c. Pole-distortion-free and tiny.
 *
 * Generated by tools/bake_studio_light.py - do not edit by hand. */

const int studio_sh_count = 9;

// RGB per coefficient, index order matches ShBasis() in the shader.
const float studio_sh_coeffs[] = {
    +2.68385088e+00f, +2.74649745e+00f, +2.88150931e+00f,
    +1.89920451e+00f, +2.14718322e+00f, +2.63629613e+00f,
    +1.44709199e+00f, +1.38205115e+00f, +1.48690906e+00f,
    +1.26712676e+00f, +1.05206445e+00f, +7.60138793e-01f,
    +1.08692370e+00f, +9.40459114e-01f, +7.55298885e-01f,
    +1.61747710e+00f, +1.61197632e+00f, +1.89375357e+00f,
    -3.85178194e-01f, -4.15638258e-01f, -4.88226109e-01f,
    +1.17283522e+00f, +9.45250602e-01f, +5.19510863e-01f,
    +4.26206169e-01f, +1.55719364e-01f, -4.57250833e-01f,
};
