/*******************************************************************************************
*
*    studio_light.h - Embedded prefiltered HDR cubemap
*
*******************************************************************************************/

#ifndef STUDIO_LIGHT_H
#define STUDIO_LIGHT_H

#include <stdint.h>
#include "raylib.h"

#define STUDIO_LIGHT_CUBEMAP_SIZE 64
#define STUDIO_LIGHT_MIP_COUNT 7

// RGB16F texels, ordered by mip and then OpenGL cubemap face:
// +X, -X, +Y, -Y, +Z, -Z. Generated by tools/bake_studio_light.py.
extern const uint16_t studio_prefiltered_cubemap[];

TextureCubemap StudioLightLoad(void);

#endif // STUDIO_LIGHT_H
